### ISSUE TITLE
The install command does not wait for user input

### ISSUE THREAD

**Issue by MatthijsBlom** [leongrdic/wsl-alias#4]
The install script does not wait for user input regarding the default alias:

```
$ curl -o- https://raw.githubusercontent.com/leongrdic/wsl-alias/master/install.sh | bash
...
Choose a command you'd like to use to call bash from Windows
Command [b]:
The installation has completed!
...
```
I did not enter an empty line there. (Tried a few times, to be sure.)

**Comment by leongrdic** [comment]
the problem was caused as the script was piped to bash which made the `read` command not able to receive stdin. i updated the readme to use a different way to load the installer script: `bash <(curl -o- ...)`
