### ISSUE TITLE
Adding alias with linux path causes syntax error

### ISSUE THREAD

**Issue by offero** [leongrdic/wsl-alias#7]
I might not be doing this properly, but I tried to create an alias to an absolute path to a program and it threw an error. 

```
C:\Users\cjk>b wsl-alias add node /home/offero/.nvm/versions/v8.15.0/bin/node
Unknown regexp modifier "/h" at -e line 1, at end of line
syntax error at -e line 1, near "/."
Execution of -e aborted due to compilation errors.
successfully added
```

Node is probably not the best example to do this with, but I'm sure there are others.

**Comment by leongrdic** [comment]
Right now, `wsl-alias` doesn't support creating aliases to absolute paths.
A solution for this would be to add this path to your $PATH variable inside `env.sh` and then add a `wsl-alias` for that command
